using System;

namespace Dangl.AVACloudClientGenerator
{
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionsService
    {
        public static string Version => "0.3.0";
        public static string CommitInfo => "Branch.master.Sha.d9ba1b0de179c44a82d66a83177c76f1a96f8c2a";
        public static string CommitDate => "2024-06-28";
        public static string CommitHash => "d9ba1b0de179c44a82d66a83177c76f1a96f8c2a";
        public static string InformationalVersion => "0.3.0+Branch.master.Sha.d9ba1b0de179c44a82d66a83177c76f1a96f8c2a";
        public static DateTime BuildDateUtc { get; } = new DateTime(2024, 7, 1, 8, 56, 16, DateTimeKind.Utc);
    }
}
